# Generated by Django 5.0.1 on 2024-04-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
