# Generated by Django 5.0.1 on 2024-04-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_category_file_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
