# Generated by Django 5.0.4 on 2024-04-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_sharedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedFile',
        ),
    ]
